# Generated by Django 4.1.7 on 2023-03-18 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cakes',
            name='description',
            field=models.CharField(default='null', max_length=250),
        ),
        migrations.AlterField(
            model_name='cakes',
            name='weight',
            field=models.CharField(max_length=250),
        ),
    ]
