# Generated by Django 4.1.7 on 2023-03-22 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_cakes_description_alter_cakes_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='cakes',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
