# Generated by Django 4.1.7 on 2023-03-15 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_mobiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('genres', models.CharField(max_length=250)),
                ('year', models.PositiveIntegerField()),
                ('language', models.CharField(max_length=100)),
                ('rating', models.PositiveIntegerField()),
            ],
        ),
    ]
